# Generated by Django 4.2.23 on 2025-09-01 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('properties', '__first__'),
        ('landlords', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rent', 'Monthly Rent'), ('security_deposit', 'Security Deposit'), ('admin_fee', 'Admin Fee'), ('cleaning_fee', 'Cleaning Fee'), ('maintenance_fee', 'Maintenance Fee'), ('late_fee', 'Late Payment Fee'), ('utility_bill', 'Utility Bill'), ('damage_charge', 'Damage Charge'), ('refund', 'Refund'), ('other', 'Other')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('upcoming', 'Payment Due Soon'), ('overdue', 'Payment Overdue'), ('final_notice', 'Final Notice'), ('custom', 'Custom Reminder')], max_length=15)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('reminder_method', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone Call'), ('in_person', 'In-Person')], default='email', max_length=15)),
                ('message_sent', models.TextField(blank=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymenttype')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='residents.resident')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Payment Received'), ('outbound', 'Payment Made')], default='inbound', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('online_payment', 'Online Payment'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction reference', max_length=100)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Payment Received'), ('verified', 'Verified'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Under Dispute')], default='pending', max_length=15)),
                ('payment_period_start', models.DateField(blank=True, null=True)),
                ('payment_period_end', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='landlords.landlord')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymenttype')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to='employees.employee')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='residents.resident')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.room')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='employees.employee')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
