# Generated by Django 4.2.23 on 2025-09-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('tenant', 'Tenant Inquiry'), ('landlord', 'Landlord Partnership'), ('contact', 'General Contact')], default='contact', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('company_name', models.CharField(blank=True, help_text='For landlord inquiries', max_length=200)),
                ('source', models.CharField(choices=[('website_contact', 'Website Contact Form'), ('website_landlord', 'Website Landlord Form'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('university_partnership', 'University Partnership'), ('agent', 'Education Agent'), ('walk_in', 'Walk-in'), ('phone_call', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='website_contact', max_length=25)),
                ('source_details', models.CharField(blank=True, help_text='Specific source details', max_length=200)),
                ('referrer_name', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='Main inquiry message')),
                ('property_address', models.TextField(blank=True, help_text='Full property address')),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('shared_apartment', 'Shared Apartment'), ('student_residence', 'Student Residence'), ('other', 'Other')], max_length=30)),
                ('number_of_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_rent_expectation', models.CharField(blank=True, help_text='Expected monthly rent', max_length=50)),
                ('property_description', models.TextField(blank=True)),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('budget_range', models.CharField(blank=True, help_text='e.g., 400-600 EUR', max_length=50)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Initial Contact Made'), ('interested', 'Showing Interest'), ('meeting_scheduled', 'Meeting/Call Scheduled'), ('proposal_sent', 'Proposal/Information Sent'), ('converted', 'Converted'), ('lost', 'Lost Lead'), ('not_interested', 'Not Interested')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('next_followup_date', models.DateTimeField(blank=True, null=True)),
                ('contact_attempts', models.PositiveIntegerField(default=0)),
                ('is_converted', models.BooleanField(default=False)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('converted_leads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp Message'), ('meeting', 'In-Person Meeting'), ('video_call', 'Video Call'), ('property_visit', 'Property Visit'), ('proposal_sent', 'Proposal Sent'), ('follow_up', 'Follow-up'), ('note', 'Internal Note'), ('status_change', 'Status Change')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', '-created_at'], name='leads_lead_status_7559b2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', '-created_at'], name='leads_lead_assigne_aefcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', '-created_at'], name='leads_lead_lead_ty_1ba554_idx'),
        ),
    ]
