# Generated by Django 4.2.23 on 2025-09-01 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'System Administrator'), ('manager', 'Operations Manager'), ('property_manager', 'Property Manager'), ('maintenance_supervisor', 'Maintenance Supervisor'), ('support_agent', 'Customer Support Agent'), ('sales_executive', 'Business Development Executive'), ('accountant', 'Accountant'), ('housekeeping_supervisor', 'Housekeeping Supervisor'), ('maintenance_technician', 'Maintenance Technician'), ('housekeeping_staff', 'Housekeeping Staff')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_manage_properties', models.BooleanField(default=False)),
                ('can_manage_landlords', models.BooleanField(default=False)),
                ('can_manage_residents', models.BooleanField(default=False)),
                ('can_handle_payments', models.BooleanField(default=False)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_handle_maintenance', models.BooleanField(default=False)),
                ('can_handle_support_tickets', models.BooleanField(default=False)),
                ('can_manage_leads', models.BooleanField(default=False)),
                ('can_manage_housekeeping', models.BooleanField(default=False)),
                ('can_access_crm', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=15)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated'), ('on_leave', 'On Leave')], default='active', max_length=15)),
                ('hire_date', models.DateField()),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('work_location', models.CharField(blank=True, help_text='Primary work location/property', max_length=100)),
                ('shift_timing', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('certifications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
