# Generated by Django 4.2.23 on 2025-09-01 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_id', models.CharField(max_length=20, unique=True)),
                ('landlord_type', models.CharField(choices=[('individual', 'Individual Owner'), ('company', 'Property Management Company'), ('investor', 'Real Estate Investor'), ('institutional', 'Institutional Owner')], default='individual', max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, help_text='German tax identification number', max_length=50)),
                ('partnership_status', models.CharField(choices=[('prospect', 'Prospect'), ('under_evaluation', 'Under Evaluation'), ('active', 'Active Partner'), ('inactive', 'Inactive'), ('terminated', 'Partnership Terminated')], default='prospect', max_length=20)),
                ('partnership_start_date', models.DateField(blank=True, null=True)),
                ('preferred_payout_schedule', models.CharField(default='Monthly', help_text='Preferred payout frequency', max_length=50)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('guaranteed_rent_preference', models.BooleanField(default=False, help_text='Prefers guaranteed rent options')),
                ('maintenance_handling', models.CharField(default='BrandenBed Managed', help_text='How maintenance should be handled', max_length=100)),
                ('preferred_communication', models.CharField(default='Email', max_length=50)),
                ('total_properties', models.PositiveIntegerField(default=0)),
                ('total_earnings_to_date', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_bd_executive', models.ForeignKey(blank=True, help_text='Business Development Executive', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandlordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('property_deed', 'Property Deed'), ('tax_document', 'Tax Document'), ('bank_details', 'Bank Details'), ('partnership_agreement', 'Partnership Agreement'), ('identity_proof', 'Identity Proof'), ('other', 'Other')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='landlord_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='landlords.landlord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
    ]
