# Generated by Django 4.2.23 on 2025-09-01 13:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('family_house', 'Family House'), ('residential_building', 'Residential Building'), ('student_residence', 'Student Residence'), ('co_living_space', 'Co-living Space')], max_length=25)),
                ('furnishing', models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-furnished'), ('unfurnished', 'Unfurnished')], default='furnished', max_length=15)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(default='Berlin', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('district', models.CharField(blank=True, help_text='Berlin district (e.g., Mitte, Kreuzberg)', max_length=100)),
                ('nearest_university', models.CharField(blank=True, max_length=200)),
                ('distance_to_university', models.CharField(blank=True, help_text='e.g., 10 mins walk, 15 mins by U-Bahn', max_length=50)),
                ('total_rooms', models.PositiveIntegerField()),
                ('total_beds', models.PositiveIntegerField()),
                ('total_washrooms', models.PositiveIntegerField()),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Area in square meters', max_digits=8)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('available_from', models.DateField()),
                ('has_wifi', models.BooleanField(default=True, help_text='High-speed WiFi')),
                ('has_security', models.BooleanField(default=True, help_text='24/7 security & support')),
                ('has_power_backup', models.BooleanField(default=True, help_text='24/7 Power Backup')),
                ('has_work_desk', models.BooleanField(default=True, help_text='Dedicated Work Desk')),
                ('has_shared_kitchen', models.BooleanField(default=True)),
                ('has_shared_lounge', models.BooleanField(default=True)),
                ('has_laundry', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('near_public_transport', models.BooleanField(default=True)),
                ('nearest_metro_station', models.CharField(blank=True, max_length=100)),
                ('distance_to_metro', models.CharField(blank=True, help_text='Walking distance to nearest station', max_length=50)),
                ('partnership_start_date', models.DateField()),
                ('partnership_end_date', models.DateField(blank=True, null=True)),
                ('expected_monthly_rent', models.DecimalField(decimal_places=2, help_text='Expected monthly rent in EUR', max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_evaluation', 'Under Evaluation'), ('under_renovation', 'Under Renovation'), ('inactive', 'Inactive'), ('terminated', 'Partnership Terminated')], default='under_evaluation', max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements for residents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('housekeeping_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_properties', to='employees.employee')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landlords.landlord')),
                ('maintenance_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_properties', to='employees.employee')),
                ('property_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room'), ('studio', 'Studio Apartment'), ('single', 'Single Occupancy'), ('double', 'Double Occupancy')], max_length=15)),
                ('area', models.DecimalField(decimal_places=2, help_text='Room area in square meters', max_digits=6)),
                ('max_occupants', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('current_occupants', models.PositiveIntegerField(default=0)),
                ('has_private_bathroom', models.BooleanField(default=False)),
                ('has_work_desk', models.BooleanField(default=True, help_text='Dedicated work desk')),
                ('has_storage', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_window', models.BooleanField(default=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monthly rent in EUR', max_digits=8)),
                ('utilities_included', models.BooleanField(default=True, help_text='All utilities included in rent')),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('blocked', 'Blocked')], default='available', max_length=15)),
                ('available_from', models.DateField()),
                ('min_contract_duration', models.PositiveIntegerField(default=6, help_text='Minimum contract duration in months')),
                ('max_contract_duration', models.PositiveIntegerField(default=12, help_text='Maximum contract duration in months')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
            options={
                'unique_together': {('property_ref', 'room_number')},
            },
        ),
    ]
