# Generated by Django 4.2.23 on 2025-09-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='max_occupants',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
