# Generated by Django 4.2.23 on 2025-09-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('total_rooms', models.PositiveIntegerField()),
                ('occupied_rooms', models.PositiveIntegerField()),
                ('occupancy_rate', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_support_tickets', models.PositiveIntegerField(default=0)),
                ('resolved_support_tickets', models.PositiveIntegerField(default=0)),
                ('average_resolution_time', models.DecimalField(blank=True, decimal_places=2, help_text='Hours', max_digits=5, null=True)),
                ('maintenance_requests', models.PositiveIntegerField(default=0)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='properties.property')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('property', 'year', 'month')},
            },
        ),
    ]
