# Generated by Django 4.2.23 on 2025-09-01 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '__first__'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(max_length=20, unique=True)),
                ('resident_type', models.CharField(choices=[('student', 'International Student'), ('local_student', 'Local Student'), ('professional', 'Working Professional'), ('intern', 'Intern')], max_length=20)),
                ('identification_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID Card'), ('student_id', 'Student ID'), ('visa', 'Visa')], max_length=15)),
                ('identification_number', models.CharField(max_length=50)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('enrollment_proof', models.FileField(blank=True, null=True, upload_to='resident_documents/')),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('employment_proof', models.FileField(blank=True, null=True, upload_to='resident_documents/')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('income_source', models.CharField(blank=True, help_text='e.g., Job, Scholarship, Family Support', max_length=100)),
                ('visa_type', models.CharField(blank=True, max_length=50)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('preferred_room_type', models.CharField(blank=True, max_length=50)),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('budget_range', models.CharField(blank=True, help_text='e.g., 400-600 EUR', max_length=50)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('applied', 'Application Submitted'), ('verified', 'Verification Complete'), ('active', 'Active Resident'), ('moved_out', 'Moved Out'), ('terminated', 'Terminated')], default='lead', max_length=15)),
                ('parent_guardian_name', models.CharField(blank=True, max_length=100)),
                ('parent_guardian_phone', models.CharField(blank=True, max_length=17)),
                ('parent_guardian_email', models.EmailField(blank=True, max_length=254)),
                ('dietary_requirements', models.CharField(blank=True, max_length=200)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions we should know about')),
                ('special_needs', models.TextField(blank=True)),
                ('verification_completed', models.BooleanField(default=False)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('agreement_signed', models.BooleanField(default=False)),
                ('orientation_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_support_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('current_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResidencyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('utilities_included', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_for_signing', 'Sent for Signing'), ('signed', 'Signed'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('special_clauses', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='residents.resident')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.room')),
            ],
        ),
    ]
