# Generated by Django 4.2.23 on 2025-09-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='resident_type',
            field=models.CharField(choices=[('student', 'International Student'), ('local_student', 'Local Student'), ('professional', 'Working Professional')], max_length=20),
        ),
    ]
