# Generated by Django 4.2.23 on 2025-09-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('properties', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=20, unique=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('one_time', 'One-time'), ('move_out_cleaning', 'Move-out Cleaning'), ('deep_cleaning', 'Deep Cleaning')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('estimated_duration', models.DurationField(help_text='Estimated time to complete')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=15)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('checklist_completed', models.BooleanField(default=False)),
                ('quality_check_passed', models.BooleanField(default=False)),
                ('before_photos', models.FileField(blank=True, null=True, upload_to='housekeeping_photos/')),
                ('after_photos', models.FileField(blank=True, null=True, upload_to='housekeeping_photos/')),
                ('completion_notes', models.TextField(blank=True)),
                ('issues_found', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ManyToManyField(related_name='housekeeping_assignments', to='employees.employee')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_schedules', to='properties.property')),
                ('quality_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checked_housekeeping', to='employees.employee')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.room')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_housekeeping', to='employees.employee')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
