# Generated by Django 4.2.23 on 2025-09-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('properties', '__first__'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('vendor_type', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('cleaning', 'Cleaning Services'), ('security', 'Security Systems'), ('general_maintenance', 'General Maintenance'), ('appliance_repair', 'Appliance Repair'), ('pest_control', 'Pest Control'), ('landscaping', 'Landscaping'), ('other', 'Other')], max_length=25)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('services_offered', models.TextField()),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('emergency_available', models.BooleanField(default=False)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='active', max_length=15)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 5.00', max_digits=3, null=True)),
                ('total_jobs_completed', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('repair', 'Repair'), ('emergency', 'Emergency'), ('inspection', 'Inspection'), ('upgrade', 'Upgrade')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Emergency'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=3)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('assigned', 'Assigned to Vendor'), ('in_progress', 'Work in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=15)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('before_photos', models.FileField(blank=True, null=True, upload_to='maintenance_photos/')),
                ('after_photos', models.FileField(blank=True, null=True, upload_to='maintenance_photos/')),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance', to='employees.employee')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('assigned_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.vendor')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='properties.property')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_maintenance', to='employees.employee')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.room')),
                ('support_ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.supportticket')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
